dist: xenial
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: aVs7M6KLr8NOfZllgZdziGhRfgYlcRSXP/7USFuVvv10eb6wsPHDFnXLCyQkauxVtJJJCx2Lz3DxP7Y2SUNC3nTlSbQ6f55FRe4qJYkayc5WY9sLRboC5hbb++09YFErnJ8WcrqhEmUuIxcxJaWpUEwoOwzVmcasVe+HIEYp+E/9Lgs3UCUUdPxqWbljUUli7eKAvBhn08joQ3ORSkHVVr9itZGM6G5l34vhoRHTDIegAEl54eLaofRCP8oLgFpsGicvxVako+Rp4lx4j13Qr14nz4rS9lJkbn/jVNADkynYuWagij2tiX5G3y6TKerYXx7CcF553oEhrHpSbHKHSUvRVXYRAnEM9612OuIFqy6to6cTl0LyLKw0xVNRRYl8xoGlRFFagzD/DGS4LbiVVN4B6TZLRo001Z/IiGKPZXB1US9cMOWnHGFM6rVYKYKpYSoHWSeTfWgb2ykgYQ+LDr5Vl0mlYVlca9c2UJnVfCh12Sb/QeqTmyp8/jwyZIVKAbUTZTNk7tyymNJFU8534sJxLBcG6gA4gGktA8jvNyNZndGysap/i3mMDRTmzfY0lpczn+xKbtrx+yovs9qq9dsaWiosALCdRB+KqvQHtnNMlvV8wBX9LTXnx/BXqHJZhV7sdf772eKOKTeheyPTO/ldzcKSIbiVFutEYbXKAac=
install:
- pip install -r requirements.txt
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_espatcontrol.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-espatcontrol --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
